// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okzhikykpwubsrhuwbto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9remhpa3lrcHd1YnNyaHV3YnRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTMyNjIsImV4cCI6MjA2NTQ4OTI2Mn0.LlOLYMdNdVEaOnvGrOIe7nXgJSU6mCFQNm4aHvenArM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);